---
- hosts: db
  become: yes
  tasks:
    - name: Instalando Postgresql Server ...
      package: name={{ item }} update_cache=yes state=latest
      with_items:
        - postgresql

    - name: Criando novo usuario no banco de dados ...
      become: yes
      become_user: postgres
      shell: psql -c "CREATE USER usuario WITH PASSWORD 'senha';"

    - name: Criando novo database ...
      become: yes
      become_user: postgres
      shell: psql -c "CREATE DATABASE telesaude;"

    - name: Concedendo permissoes ao usuario ...
      become: yes
      become_user: postgres
      shell: psql -c "GRANT ALL PRIVILEGES ON DATABASE telesaude TO usuario;"

    - lineinfile:
        dest: /etc/postgresql/9.3/main/postgresql.conf
        regexp: "^#listen_addresses = 'localhost'"
        line:   "listen_addresses = '*'"

    - lineinfile:
        dest: /etc/postgresql/9.3/main/pg_hba.conf
        regexp: "^host    all             all             127.0.0.1/32            md5"
        line:   "host    all             all             0.0.0.0/0            md5"

    - service:
        name: postgresql
        state: restarted
