---
- hosts: web
  sudo: yes
  tasks:
    - name: Instalando pacotes necessarios ...
      package: name={{ item }} update_cache=yes state=latest
      with_items:
        - python3
        - python3-pip
        - git-core 
        - libpq-dev 
        - postgresql-client
    - name: Clonando repositorio ...
      git: repo=https://github.com/vinigfer/desafio_telesaude.git dest=/home/vagrant/desafio_telesaude
    - name: Instalando pacotes python com pip3 ...
      pip: 
        requirements: /home/vagrant/desafio_telesaude/requirements.txt
        executable: pip3
    - name: Adicionando resolucao de DNS para o nome 'database' ...
      shell: sed -i '1 i\192.168.1.147   database' /etc/hosts

    - name: Rodando migrations ...
      shell: python3 desafio_telesaude/manage.py migrate

    - name: Iniciando servidor Python ...
      shell: cd desafio_telesaude && gunicorn --bind 0.0.0.0:8000 telesaude.wsgi &
