---
- hosts: web
  become: yes
  tasks:
    - name: Instalando pacotes necessarios ...
      package: name={{ item }} update_cache=yes state=latest
      with_items:
        - python3
        - python3-pip
        - git-core 
        - libpq-dev 
        - postgresql-client

    - name: Clonando repositorio ...
      git: repo=https://github.com/vinigfer/desafio_telessaude.git dest=/home/vagrant/desafio_telessaude

    - name: Instalando pacotes python com pip3 ...
      pip: 
        requirements: /home/vagrant/desafio_telessaude/requirements.txt
        executable: pip3

    - name: Adicionando resolucao de DNS para 'database' ...
      lineinfile:
        dest: /etc/hosts
        line: "192.168.1.147   database"

    - name: Rodando migrations ...
      shell: python3 desafio_telessaude/manage.py migrate

    - name: Iniciando servidor Python ...
      shell: cd desafio_telessaude && gunicorn --bind 0.0.0.0:8000 telessaude.wsgi &
