---
- hosts: web
  sudo: yes
  tasks:
    - name: Instalando pacotes necessarios ...
      package: name={{ item }} update_cache=yes state=latest
      with_items:
        - python3
        - python3-pip
        - git-core 
        - libpq-dev 
        - postgresql-client
    - name: Clonando repositorio ...
      git: repo=https://github.com/vinigfer/desafio_telesaude.git dest=/home/vagrant/desafio_telesaude
    - name: Instalando pacotes python com pip3 ...
      pip: 
        requirements: /home/vagrant/desafio_telesaude/requirements.txt
        executable: pip3
