---
- hosts: db
  sudo: yes
  tasks:
    - name: Instalando Postgresql Server ...
      package: name={{ item }} update_cache=yes state=latest
      with_items:
        - postgresql
    - name: Criando novo usuario no banco de dados ...
      shell: sudo -u postgres psql -c "CREATE USER usuario WITH PASSWORD 'senha';"

    - name: Criando novo database ...
      shell: sudo -u postgres psql -c "CREATE DATABASE telesaude;"

    - name: Concedendo permissoes ao usuario ...
      shell: sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE telesaude TO usuario;"

    - name: Configurando acesso externo ao database (parte I) ...
      shell: sed -ie "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/9.3/main/postgresql.conf

    - name: Configurando acesso externo ao database (parte II) ...
      shell: sed -ie "s/# IPv4 local connections:/# IPv4 local connections:\nhost    all             all             0.0.0.0\/0          md5/g" /etc/postgresql/9.3/main/pg_hba.conf

    - name: Reiniciando Postgresql ...
      shell: service postgresql restart
