# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/trusty64"
    db.vm.hostname = 'db'
    # Atencao: devemos garantir que esse endereco estara disponivel para 
    # a VM. Esse mesmo IP tambem esta configurado no playbook_web.yml
    # Interface brigde tambem pode mudar de nome conforme o computador.
    db.vm.network "public_network", ip: "192.168.1.147", bridge: "wlan0"
    
    db.vm.provider "virtualbox" do |vb| 
      vb.memory = "512"
      vb.cpus = 1
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_db.yml"
    end
  end

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/trusty64"
    web.vm.hostname = 'web'
    web.vm.network "forwarded_port", guest: 8000, host: 8000

    web.vm.provider "virtualbox" do |vb| 
      vb.memory = "512"
      vb.cpus = 1
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_web.yml"
    end
  end

end
