# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/trusty64"
    web.vm.hostname = 'web'
    web.vm.network "forwarded_port", guest: 80, host: 8000

    web.vm.provider "virtualbox" do |vb| 
      vb.memory = "512"
      vb.cpus = 1
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

#  config.vm.define "db" do |db|
#    db.vm.box = "ubuntu/trusty64"
#    db.vm.hostname = 'db'

#    db.vm.provider "virtualbox" do |vb| 
#      vb.memory = "512"
#      vb.cpus = 1
#    end

#    config.vm.provision "ansible" do |ansible|
#      ansible.playbook = "playbook.yml"
#    end
#  end

end
