FROM ubuntu:14.04

ADD configure.sh /root/configure.sh
RUN /root/configure.sh
#Roda as migrations e depois inicia App django quando o container terminar de subir. 
#Importante adicionar 0.0.0.0:8000, do contrario o container acessa apenas localhost interno
ADD startup.sh /root/startup.sh
CMD /root/startup.sh
